### ISSUE TITLE
build for iOS

### ISSUE THREAD

**Issue by mbsanchez** [OpenVPN/openvpn3#1]
Hi, it's a good news that you have shared new updates of openvpn3 on github.

I have 2 related questions:
1. What are the dependencies to build openvpn3 for iOS?
2. How can I integrate it with NEVPNManager or something else?

**Comment by mattock** [comment]
@jamesyonan knows best, but plaisthos on #openvpn-devel has also managed to build OpenVPN 3 on iOS as well as integrate it to his OpenVPN for Android app.

**Comment by mbsanchez** [comment]
Great, How can I contact they?

**Comment by mattock** [comment]
I hope @jamesyonan notices this himself. You can reach plaisthos on the #openvpn-devel IRC channel.

**Comment by schwabe** [comment]
@mbsanchez Even if you build for iOS you would not be able to publish it on the app store since the license (AGPL3) forbids it.

**Comment by mattock** [comment]
@mbsanchez : extending on the answer from @schwabe ... Apple Appstore places several restrictions on app distribution and use. It is these restrictions that are incompatible with GPL (including AGPLv3). The only way a GPL-licensed application can be published in the Apple Appstore is by relicensing the whole codebase using a different, typically proprietary, license. Relicensing is only possible for the copyright holder, that is, OpenVPN Technologies, Inc.

**Comment by chipitsine** [comment]
@mattock, it seems that relicensing is only possible for software author. i.e. if some GPL code is written by some person, only that person can relicense his own piece of code.

**Comment by cron2** [comment]
Hi,

On Mon, Sep 26, 2016 at 01:00:11AM -0700, Ilya Shipitsin wrote:
> @mattock, it seems that relicensing is only possible for software author. i.e. if some GPL code is written by some person, only that person can relicense his own piece of code.

It is possible if the original author agrees, by signing a CLA or 
similar.  Since that is not possible to achieve for all contributors
to OpenVPN 2.x, OpenVPN 3 is a complete rewrite that is not sharing
any code with 2.x

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by 986444785** [comment]
i need openvpn ios demo

**Comment by cron2** [comment]
Hi,

On Wed, Oct 26, 2016 at 08:05:03PM -0700, 986444785 wrote:
> i need openvpn ios demo

openvpn for ios is available in the app store...

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by pronebird** [comment]
@schwabe I am sure you can publish if your entire work is open sourced

**Comment by schwabe** [comment]
@pronebird nope, the GPLv3 does not allow you to put it on the app store. See also http://apple.stackexchange.com/questions/6109/is-it-possible-to-have-gpl-software-in-the-mac-app-store as starter for the problems.

**Comment by pronebird** [comment]
@schwabe bummer, that's a very frustrating choice of license giving that we live in mobile era. Are there any options to make this work available for use with AppStore?

**Comment by schwabe** [comment]
@pronebird probably the only way is to ask OpenVPN inc if they can add sell you a different license or add clause to this code stating that publishing the code on the app store is allowed as long as all other terms that do not conflict with the app store license are fullfilled (e.g. provinding source code).

**Comment by dsommers** [comment]
@pronebird One of the reasons the iOS cannot become fully open source is due to OpenVPN Technologies had to sign an NDA with Apple to get access to the needed system privileges to configure and run a VPN tunnel on iOS.  This is very unfortunate, and everyone (both company and community) would want this very differently.  But the entity sitting on the solution to fix this is Apple alone.  As long as they prefer this closed way of working, only part of the code can be open sourced (basically what is not iOS specific).  And the code which is open sourced, is the OpenVPN 3 Core here on github which is a core library for implementing OpenVPN tunnels.

So until Apple changes and becomes more friendly towards open source projects, we can't do anything else.  But I am truly sorry for this, I do wish it was differently.  Closing this ticket now, as we can't provide any solution for iOS as things are now.

**Comment by yegors** [comment]
@dsommers "One of the reasons the iOS cannot become fully open source is due to OpenVPN Technologies had to sign an NDA with Apple to get access to the needed system privileges to configure and run a VPN tunnel on iOS. "

That's no longer the case. 

> 
> I’m responding to your question about VPN transports on iOS.  You wrote:
> 
> >  OpenVPN Connect (…) has this capability, but it seems they were
> >  granted exclusive access to some private APIs which are not available
> >  to other developers.
> 
> Historically that was the case but, starting with iOS 9, you can create a custom VPN transport using public APIs, namely the packet tunnel and app proxy providers supported by the Network Extension framework.  For an introduction to these facilities, watch WWDC 2015 Session 717 “What’s New in Network Extension and VPN”.
> 
> <https://developer.apple.com/videos/play/wwdc2015/717/>
> 
> IMPORTANT: At the end of that talk we say that Apple must grant you special entitlements to use these APIs.  That restriction was recently lifted.  Any developer can now create Network Extension providers. The following DevForums post has the details.
> 
> <https://forums.developer.apple.com/thread/67613>
> 
> You should also take a look at the NetworkExtension framework reference, which includes a bunch of useful info, and the SimpleTunnel sample code.
> 
> <https://developer.apple.com/reference/networkextension>
> 
> <https://developer.apple.com/library/ios/samplecode/SimpleTunnel/>
> 
> Finally, I’ve attached a small test project, QNEPacketTunnel, that I’ve created for doing simple VPN tests.
> 
> IMPORTANT: QNEPacketTunnel has not yet been formally reviewed, so it is not yet official Apple sample code.  Please don't redistribute it outside of your immediate organisation.
> 
>                    *                   *                   *
> 
> I should stress that creating a new VPN transport is a major undertaking.  DTS can assist you with parts of that (the code that interacts with the system) but you are responsible for writing (or acquiring) the code that implements the core VPN functionality.
> 
> Share and Enjoy
> --
> Quinn "The Eskimo!"
> Apple Developer Relations, Developer Technical Support, Core OS/Hardware

**Comment by gardion** [comment]
Slightly off-topic but then again, may be relevant: We are currently pondering creating an open source fork of schwabe/ics-openvpn for our special needs (https://github.com/gardion/android-client), an iOS client is in the cards in the next months.
While researching OpenVPN we became aware of https://www.wireguard.io. Looks like a great replacement of IPSEC/OpenVPN in certain situations.
Have a look if you need secure and performant connections and you control both endpoints.

**Comment by yegors** [comment]
Wireguard looks really great, however it suffers from the same issue as OpenVPN for ios: GPL license.

**Comment by gardion** [comment]
What license would be acceptable? MIT, BSD? I'll ask the creator of WireGuard if he'll consider dual licensing.

**Comment by yegors** [comment]
MIT and BSD should work, App store specifically prohibits GPL licensed code.

**Comment by gardion** [comment]
Just had a chat with Jason from WireGuard. He is aware of this issue and says the code that will be run on/required for the iOS client won't be GPL2. I haven't found out what the license will be, but I will report back once i do @zx2c4

**Comment by zx2c4** [comment]
What I said specifically is that the current GPLv2 WireGuard code is written for the Linux kernel, which isn't code for iOS, so the current GPLv2 code doesn't need to be relicensed for iOS, since it won't run there anyway. It seems likely to me that future other code written explicitly for iOS would use an iOS-compatible license.

How this is related to OpenVPN, or what a discussion of WireGuard licensing is doing here, I do not know. So, I'll buck out of this strange thread. Just thought I'd chime in since I was paraquoted.

---

Good luck with OpenVPN 3, guys! Seems like some nice improvements are in the fold.

**Comment by dsommers** [comment]
OpenVPN Technologies, Inc have licensed the OpenVPN 3 code base with AGPLv3.  As far as I know, this is not going to change any time soon, if at all.

In the contributor agreement, present in the repository, there is a clause which ensures OpenVPN Technologies, Inc is allowed to re-license the code; which is there to allow this code base to be present in annoyingly strict appstores like Apple's. There is however a guarantee that all modifications done to the re-licensed code will also be added to the AGPLv3 licensed code.  This re-license allowance is only permitted to OpenVPN Technologies, Inc and nobody else.

**Comment by jiangyancong** [comment]
@yegors then do you think it's possible to integrate OpenVPN library with Network Extension framework technically? From the official response, it seems possible but I don't know whether there's other issue.

**Comment by serjooo** [comment]
Question, just want an answer to sum up all the above and make sure if I understood everything correctly. It is possible to create an application that reads an .ovpn file with the new NetworkExtension and NEVPNManager; however, you would need to implement it all from scratch and even if you are successful doing that, Apple would still not allow your application to be released because OpenVPN is under the GPLv3 license. Is what I stated correct?

**Comment by schwabe** [comment]
@serjooo correct.

**Comment by mattock** [comment]
OpenVPN 3 is under AGPLv3, but the effect is the same. I believe most copyleft licenses are a no-go for Apple Appstore.

**Comment by serjooo** [comment]
@schwabe So it is useless making a VPN application using OpenVPN in the first place... Sad.. Is there any other workaround for this?

**Comment by mattock** [comment]
Besides rooting your iOS device - no.

**Comment by serjooo** [comment]
@schwabe @mattock  Thank you for your quick responses very useful, saved me time before I started actual implementation on the front end. Been researching for a few days only to find out that my initial plan for this application is a dead end. Great discussion here guys thank you all for the rich information provided here. I'll keep following the thread if any change is to come about. Thank you all for your time and effort much appreciated.

**Comment by moduspwnens** [comment]
You certainly don't need to root. You don't even need to request entitlements for it any more. At the minimum you need working code and the ability to build on a device. You don't need to use private APIs or break out of the sandbox.

@serjooo's question mentioned implementing a client from scratch, which would involve no code from OpenVPN. I wasn't aware the license covers protocol-compliant usage by clients with none of their code.

**Comment by mattock** [comment]
@moduspwnens : but you would need to root to install applications not in the Appstore, right?

**Comment by moduspwnens** [comment]
Not if you build them onto the device yourself from Xcode.

**Comment by yegors** [comment]
You could always distribute the app through TestFlight or Crashlytics Beta. :)

**Comment by serjooo** [comment]
@moduspwnens @schwabe  Thus we come to a conclusion if I were to create my own iOS application, that reads .ovpn configuration file. The application can be submitted to the app store with no problem, because I am not using any of OpenVPN's actual code.

**Comment by schwabe** [comment]
@serjooo yes as long as your code is free from GPL code  you can do that. Otherwise OpenVPN's own applications would not be allowed on the app store.

**Comment by solanki12** [comment]
Any progress ? how we can implement Open VPN for IOS or fully coding Open VPN from scratch with Network Extension Framework any guide on that ?

**Comment by mattock** [comment]
@solanki12 implementing OpenVPN from scratch is not a trivial task, even if you only implement the client side. Looking at Git logs it took James about two years to get the first working iOS build out. All the documentation there is is on this project's GitHub repository.

Is there a particular reason why you can't just use OpenVPN Connect for iOS?

**Comment by anatoli26** [comment]
From reading this entire issue I'm getting a conclusion that for the latest iOS it's possible to have a custom OpenVPN app without any special agreement with Apple by creating a

> VPN transport using public APIs, namely the packet tunnel and app proxy providers supported by the Network Extension framework,

so the only thing that would be needed is a non-GPL license from OpenVPN Technologies, Inc for the code to comply with the AppStore license requirements, right?

If my understanding is correct, does someone here know if OpenVPN Technologies, Inc practice this and whom should I contact?

**Comment by mattock** [comment]
@anatoli26 I believe the "Sales and licensing" email address on the openvpn.net [Contact us](https://openvpn.net/index.php/contact-us-sp-989947891.html) page is the right place to ask.

**Comment by solanki12** [comment]
Thanks Anatoli,
I have talked about that, but Express VPN App is giving Open VPN services
without Open VPN Connect, Don't know how ?

Thanks for reaching out. The iOS Connect Client is not open, and we cannot
open it the way the Apple plugins work.



We cannot allow a rebrand of our IOS Client even with a commercial
agreement--- I don't believe that will change even with our upcoming
Network Extensions version as Network Extensions still requires a vendor
identity.



Apple did not open the extension.  Express VPN is still using IPSec (not
OpenvPN) protocol.



if they want to develop their own client they can only do this only on
Android... OR IOS using the method you described below;



*Users would need to install both your app and our OpenVPN Connect app, and
then use Intents to load profiles and start VPN connection from their app
to the OpenVPN Connect app.*

*Most of the instructions for doing this is in the in-app help.*







Regarding the OpenVPN Connect on Android—we are not permitting any
rebranding via commercial license at this time.





Kind regards,



Gary McCloud

Head of Business Development

*OpenVPN Inc.* <http://www.openvpn.net/>

7901 Stoneridge Dr. Suite 540

Pleasanton, California  94588





*From:* Alishah Solanki [mailto:alishah.solanki@gmail.com]
*Sent:* Monday, May 8, 2017 12:20 PM
*To:* Gary McCloud <gary@openvpn.net>
*Subject:* Re: OpenVPN Business Development

**Comment by yegors** [comment]
> Apple did not open the extension.  Express VPN is still using IPSec (not
> OpenvPN) protocol.

That is not true. I asked ExpressVPN support about this, as they offer "TCP and UDP" protocols in their iOS app.

> Hi Alex,
> 
> Thanks for contacting ExpressVPN support.
> 
> UDP and TCP are both OpenVPN. You can check this link to read about connection protocols: https://www.expressvpn.com/internet-privacy/protocols/
> 
> Kind regards,
> John @ ExpressVPN

Unless they are blatantly lying, they are using OpenVPN in their branded iOS app.

**Comment by anatoli26** [comment]
Mm... looks like an official reply from OpenVPN Inc is needed. In my case I don't need the Connect front-end, just the back-end, i.e. the protocol implementation to pass all communications of my app with my server via differently-configured OpenVPN tunnels (user-selectable from within the app).

**Comment by anatoli26** [comment]
OK, I've just seen the WWDC 2015 presentation video where the topic is explained in a lot of detail, with actual code and everything: https://developer.apple.com/videos/play/wwdc2015/717/ (if you don't have safari, you may download the video from the Resources tab below).

From this video I understand that the only thing needed now (since iOS 9) for own OpenVPN client implementation on iOS is the OpenVPN *protocol* implementation that one would insert into the SimpleTunnel app (that is provided by Apple with a 3-clause BSD-like non-restrictive license, as a working example for everything VPN related, including establishing the tunnel, reading/writing the actual network data, etc., just no encryption) + to request the special entitlement (explained at the last 3 min of the video), though I have no idea what are the conditions to become approved.

At the same time (I may be wrong on this, please correct) AFAIK there's no OpenVPN protocol implementation published for iOS (in swift), so if someone makes his/her own OpenVPN protocol implementation in swift that would sufficiently differ from the C++ server implementation, the copyright holder for that swift code would be the person writing it, so no GPL, nor any other restrictions of any type, and the resulting openvpn-enabled app could be published as closed-source. Am I right?

**Comment by solanki12** [comment]
Anatoli,
by using Network Extension Framework of iOS, by making custom tunneling how
can i implement open vpn protocol cause i cant connect to it through custom
tunneling using UDP and TCP ? if you can guide me ?

**Comment by solanki12** [comment]
yes Anatoli,you are right we cam write our own implementation in swift
using network extension as closed source.

**Comment by anatoli26** [comment]
Probably if enough users are interested, we could crowdfund the protocol implementation for iOS to be implemented under non-strict open-source license like BSD or MIT so everyone could use it in any type of project, also no issues with appstore. At the same time it would be open so whoever wants could help developing it further and inspect it for bugs.

**Comment by solanki12** [comment]
I am interested, we can write a open source code

**Comment by anatoli26** [comment]
Probably we should start by asking OpenVPN Technologies, Inc if there's any reasonable price that they would accept for developing and releasing OpenVPN protocol for iOS under BSD/MIT license. Depending on the price, IMO this would be the best option.

If they are not interested, probably a similar question should be asked to WireGuard developers (in my case I don't have any special attachment to OpenVPN apart from needing a strong crypto implementation).

**Comment by solanki12** [comment]
OK, can you ask about that to Open VPN Technologies, Inc ?

**Comment by houmie** [comment]
@anatoli26 Hi, I was wondering if you managed to make any further progress on this? I went through this whole discussion, and see conflicting statements, especially from Mr. McCloud from OpenVPN and then from ExpressVPN. So is the protocol still under license and the whole situation is hopeless, or can something be built as non-GPL license after all?

**Comment by dsommers** [comment]
@houmie What are the conflicting statements?

The situation currently is:

- OpenVPN Connect on iOS is a proprietary application, which embeds both the open sourced OpenVPN 3 core library (this project) plus a proprietary "glue layer".  The "glue layer" integrates the core library with the iOS APIs and some kind of GUI.
- The iOS APIs used are not available to other developers without an explicit agreement, including an NDA.
- Since OpenVPN Connect currently makes use of these closed iOS APIs, it cannot be fully open sourced.  (What can be opened up, is already opened up)
- Newer iOS releases provides Network Extension Framework, which will in time replace the proprietary/closed iOS APIs.  This API does not require any NDA or other agreements with Apple
- The OpenVPN wire protocol (the data stream between VPN clients and server) is not closed or patented as is.  So anyone who writes their own OpenVPN wire protocol implementation from scratch, may do so without any issues.  But it is a flexible and advanced protocol, which changes depending on which features/options being used.
- Apple seems to not appreciate GPL licensed applications.  That makes it hard to use the OpenVPN 3 Core library into applications to be available via the Apple appstore.  To circumvent that scenario, the app must therefore carry a license Apple accepts.  To be able to do that legally to provide an alternative iOS based OpenVPN app, it will be needed to re-implement a OpenVPN wire protocol library under a different license.
- There are no current plans to open source the iOS (or Android) OpenVPN Connect app.
- OpenVPN Connect is also currently not available for re-branding

Did I forget anything?

**Comment by schwabe** [comment]
@dsommers That OpeNVPN Inc can use the OpenVPN 3 C++ implementation under a different license than anyone else (AGPL3) because that is just the way it is licensed

**Comment by dsommers** [comment]
That is correct, @schwabe!  Thanks.  By the way, the license has been changed from AGPLv3 to GPLv3 for the OpenVPN 3 Core library.

**Comment by anatoli26** [comment]
My 2 cents:

> Apple seems to not appreciate GPL licensed applications.

Apple has no problem with GPL, as long as no contributor for the GPL'ed part in question starts making demands of non-compliance of AppStore terms with GPL. In this particular case, if someone takes the OpenVPN 3 core library as-is, creates a GUI and publishes it in AppStore, OpenVPN Inc. could remove it from there by saying that AppStore license doesn't comply with GPL (for its library) and Apple effectively would remove it.

> OpenVPN Connect is also currently not available for re-branding

True, as long as you don't use OpenVPN Inc's paid server product, Access Server. If you're willing to use Access Server, you could reach a deal with OpenVPN Inc for the client library.

> The iOS APIs used are not available to other developers without an explicit agreement, including an NDA. Since OpenVPN Connect currently makes use of these closed iOS APIs, it cannot be fully open sourced. (What can be opened up, is already opened up). Newer iOS releases provides Network Extension Framework, which will in time replace the proprietary/closed iOS APIs. This API does not require any NDA or other agreements with Apple.

The Network Extension framework is available since 2015 and iOS 9, I don't see any problem here.

> The OpenVPN wire protocol (the data stream between VPN clients and server) is not closed or patented as is. So anyone who writes their own OpenVPN wire protocol implementation from scratch, may do so without any issues.

Though generally true, you should take a lot of care with this approach, as copyright claim may be quite broad, i.e. if you just convert the current code from C++ to, say, Go, this would be a derivative work. Basically, to reach a high degree of no copyright violation, you should have 2 teams: one creates a formal specification of the functionality inspecting the existing code and the other writes the new code using this specification (i.e. not seeing any part of the existing code).

For this approach it's easier to find an alternative much simpler VPN wire protocol (like WireGuard). Anticipating your question, WireGuard is not ready for prime time yet, though their solution from a technical PoV is quite interesting.

**Comment by dsommers** [comment]
>>  Apple seems to not appreciate GPL licensed applications.

> Apple has no problem with GPL, as long as no contributor for the GPL'ed part in question starts making demands of non-compliance of AppStore terms with GPL [... ] OpenVPN Inc. could remove it from there by saying that AppStore license doesn't comply with GPL (for its library) and Apple effectively would remove it.

Any application implementing or using the OpenVPN 3 Core library must be GPLv3, unless a specific grant have been given to the developer(s).  https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL
And it gets even cleared when realising that the current design does not enable the OpenVPN 3 Core library to be built as a dynamic library; as of now it must be statically linked.

So if an iOS app is introduced to the Apple Appstore not being GPL and implementing OpenVPN 3, that is effectively ignoring the GPLv3 license - which is **explicitly _not_ allowed**, as the way to implement OpenVPN 3 is by statically linking the library.

If an iOS app is accepted into the Apple Appstore **and** being GPL licensed, then everything is fine.


In regards to Wireguard.  Yes, they have an interesting project going on, and it will be interesting to see how that develops.  But also bear in mind that OpenVPN have been developed since early 2000, the OpenVPN 3 Core library started its development 5-6 years ago, and builds upon the wire protocol from the earlier releases.  And the OpenVPN 2.x code base (which is currently needed to use on the server side) have been through several independent security audits.  So if software security is a concern, I'd choose OpenVPN over Wireguard nowadays.  Wireguard is only 18 months old and still under heavy development.  Once Wireguard have stabilized and is ready for some proper scrutiny and security audits, then we will see how well it truly fares.  But that project is definitely breaking new grounds, which is great!  Innovation is always needed and we can all learn from it.

Just one detail where Wireguard is a bit misleading . _"It is even capable of roaming between IP addresses, just like Mosh."_  OpenVPN is also capable of doing that, through the "peer-id" reference in the wire packets.

**Comment by anatoli26** [comment]
> Any application implementing or using the OpenVPN 3 Core library must be GPLv3

Sure. What I wanted to say is that even if a GPL app using the OpenVPN library is published, OpenVPN Inc could block it (make it disappear from AppStore) if they would like to. The destiny of such an app would be in the hands of OpenVPN Inc., no matter the license. And since OpenVPN Inc. doesn't look like willing to see alternative Connect implementations out there (even if they are GPL), this is not a viable route.

> if software security is a concern, I'd choose OpenVPN

Sure, me too, though with 2 "but"s. The first "but" is that for a reason I'm not aware of, OpenVPN Inc. choses not to relicense the client library (aka the protocol implementation) or the entire Connect app to anybody, so this way this great solution is not available to anyone who doesn't use their Access Server.

For example, a similar project in terms of license and business model is Linphone by Belledonne Communications. It's a VoIP solution (softphone + server + libs), available under GPL and proprietary. But they do explicitly allow to reuse the app (i.e. publish it in AppStore) to anyone if it's released under GPL and do offer proprietary license if one wants to release a proprietary version of the app or to embed their library to a proprietary product. The cost is about $10K-50K/year and this is a flexible and affordable solution. They even offer to re-brand the app and publish it for you in the AppStore. Why OpenVPN Inc doesn't chose this route is outside of my understanding. I'm sure most of the VPN services (and there are hundreds of them) would pay some $20-50K/year for their library or the Connect app itself to adapt it to their services.

The second "but" is that, though the code is many years old, there are vulnerabilities that are still discovered without too much effort even after a number of security audits. And here, IMO, the most important factor for security is simplicity of the code and the solution as a whole. And OpenVPN is not that simple as it could appear. In comparison, WireGuard is much, much simpler and cleaner, so much easier to audit. This is their most prominent "sales point" and IMO it's true. But they lack a client library, there's no stand-alone server in C/C++ (their server component works only soldered with the Linux kernel and there are incomplete ports in Rust and Haskell), so the project is not even in an alpha stage.

**Comment by dsommers** [comment]
>  there are vulnerabilities that are still discovered without too much effort even after a number of security audits.

Well, that sounds more like FUD.  Do you claim there exists known issues in the code which have not been resolved yet?  I am a member of the security@openvpn.net mailing lists which handles such issues.  To my knowledge, we have processed all the known critical issues, which have resulted in complete releases.

There is one issue which is under investigation, though, but from the current look of it it requires a more obscure configuration to be of concern - so that is not what we'd consider a critical issue. And that is the only open issue which we have been made aware of since our last releases.

If you have access to any issues which can be exploited, an **especially** if it can be exploited _"without too much effort"_, then we would definitely appreciate to see your findings so we can fix them.

But the OpenVPN 3 code base have not been through a third party security audit yet.  But that is something which will be looked into as well.

**Comment by dsommers** [comment]
>  Since OpenVPN Inc. doesn't look like willing to see alternative Connect implementations out there (even if they are GPL), 

OpenVPN Technologies have no issues with other GPL based clients being developed and distributed, based on the OpenVPN 3 Core library or any other approach.  If someone re-implements the OpenVPN wire protocol, that is also most likely fine (depends on how the re-implementation is done).

If you can get Apple Appstore to accept a GPL licensed product into their store, please do.  But it will not be tolerated by OpenVPN Technologies if that product is re-licensed to anything else than GPL.  The license of the OpenVPN 3 (or OpenVPN 2) must be used, as mandated by the GPL license.

What is not happening now, is open sourcing the OpenVPN Connect client - which essentially is just a graphical front-end using the OpenVPN 3 core library under the hood.  This is due to the tighter integration with both PrivateTunnel and OpenVPN Access Server.  But the OpenVPN 3 Core library contains everything needed to build brand new clients, and that is GPLv3 licensed.

> so this way this great solution is not available to anyone who doesn't use their Access Server.

That is not true.  It is possible to import an existing configuration not related to AS or Private Tunnel.  I have not checked on iOS; but did run an extra test on OpenVPN Connect on Android to verify this claim.  I connected to my own non-AS servers without any issues at all.

**Comment by cron2** [comment]
Hi,

On Thu, Aug 24, 2017 at 11:30:20PM +0000, David Sommerseth wrote:
> > so this way this great solution is not available to anyone who doesn't use their Access Server.
> 
> That is not true.  It is possible to import an existing configuration not related to AS or Private Tunnel.  I have not checked on iOS; but did run an extra test on OpenVPN Connect on Android to verify this claim.  I connected to my own non-AS servers without any issues at all.

The iOS Connect client can handle normal .ovpn configs just fine - if you
do not have AS at hand and/or do not "inline" configs it's somewhat of a
nuisance to get them onto the iOS devices, but it can be done (we do it
via https downloads).  A few obscure options are not supported, but normal
stuff just works.

But I think the comment was more about "if you use AS, OpenVPN Connect
will offer customized iOS clients" - not sure if that is true, one would
need to talk to sales :-) - but I could easily see OpenVPN tech offer that 
to a customer with a 10.000 user license for AS...

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by AnhTVc** [comment]
i public openvpn app and no have any issue from apple. 
my app: mplus vpn

**Comment by dsommers** [comment]
> i public openvpn app and no have any issue from apple.
> my app: mplus vpn

Where can we see your source code?

**Comment by AnhTVc** [comment]
Please refer to my repository

**Comment by dsommers** [comment]
> Please refer to my repository

I do not see the code for the mplus vpn app anywhere; that's the code which you need to share - using an AGPLv3 (or compatible) license, according to the AGPLv3 license of OpenVPN 3:

> [...] you have permission to link or combine any covered work with a work licensed under version 3 of the GNU General Public License into a single combined work, and to convey the resulting work. The terms of this License will continue to apply to the part which is the covered work, **but the work with which it is combined will remain governed by version 3 of the GNU General Public License.**

[GNU AGPLv3 license](https://www.gnu.org/licenses/agpl-3.0.html)

**Comment by LightSide-Alex** [comment]
Is it still not legally possible to distribute applications on AppStore with OpenVPN 3?

**Comment by dsommers** [comment]
> Is it still not legally possible to distribute applications on AppStore with OpenVPN 3?

As long as Apple does not accept GPL licensed software into their AppStore, distributing apps in the AppStore would be a violation to Apple's own restrictions.
