### ISSUE TITLE
Non-administrator user run

### ISSUE THREAD

**Issue by ginozh** [OpenVPN/openvpn3#101]
On windows10, after compiling the client, I can only use the administrator account to run correctly. Is there any way to run with a non-administrator account?

**Comment by lstipakov** [comment]
Elevated privileges are requited to set up IP address and routing. However, recently we have added separate "agent" component which runs as service under SYSTEM account and takes care of that stuff, so that test client could be run by non-privileged user. 

Here is how it works:

* run `ovpnagent.exe install` in Administrator command prompt
* run `ovpncliagent.exe client.ovpn` in (non-Administrator) command prompt

You could download latest build artifacts from https://ci.appveyor.com/project/openvpn/openvpn3/build/artifacts. Note that if you use agent from appveyor build, you need to create `omi_exe_path` key of `REG_SZ` type and any value (empty string works) at `HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN` path. This is not needed if you build agent yourself and don't define `OPENVPN_AGENT_START_PROCESS`.

**Comment by ginozh** [comment]
@lstipakov Thank you for your answer!
After running ovpnagent.exe install in Administrator command prompt, i got an error message when I started OpenVPN Agent ovpnagent in Windows Services:
The OpenVPN Agent ovpnagent service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs.

How can I solve this problem?

**Comment by ginozh** [comment]
@lstipakov Thank you for your answer!
After running ovpnagent.exe install in Administrator command prompt and starting OpenVPN Agent ovpnagent Service, i got some error messages in agent.log when I ran ovpncliagent.exe client.ovpn in (non-Administrator) command prompt:
Fri Feb 21 13:58:29 2020 OpenVPN Agent 0.1.0 [OpenSSL] built on Feb 21 2020 11:28:08
Fri Feb 21 13:58:30 2020 HTTP Listen: http-listen \\.\pipe\ovpnagent NamedPipe 4 !ssl
Fri Feb 21 13:58:30 2020 HTTP Listen: http-listen \\.\pipe\ovpnagent NamedPipe 4 !ssl
Fri Feb 21 13:58:30 2020 HTTP Listen: http-listen \\.\pipe\ovpnagent NamedPipe 4 !ssl
Fri Feb 21 13:58:30 2020 HTTP Listen: http-listen \\.\pipe\ovpnagent NamedPipe 4 !ssl
Fri Feb 21 13:58:38 2020 connection from C:\test\ovpncli\Debug\ovpncliagent.exe
Fri Feb 21 13:58:38 2020 NETWORK_RECV_ERROR
Fri Feb 21 13:58:38 2020 INSTANCE STOP : E_TCP : HTTPCore TCP: NETWORK_RECV_ERROR

How can I solve this problem?

**Comment by ginozh** [comment]
@lstipakov The problem is solved, need to put ovpncliagent.exe and ovpnagent.exe into the same directory.
Thank you for your help!

**Comment by lstipakov** [comment]
@ginozh glad to see it works!

This is a security measure to enforce having agent and client in the same directory. You could disable it for testing by adding define OVPNAGENT_DISABLE_PATH_CHECK to both client and agent projects.
