### ISSUE TITLE
What happened to `allow-pull-fqdn` and `route <hostname>` ?

### ISSUE THREAD

**Issue by brsolomon-deloitte** [OpenVPN/openvpn3#195]
OpenVPN 2.x [supported allow-pull-fqdn](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/) and specifying a `--route network` as a DNS resolvable name.

This seems to have been dropped completely in OpenVPN 3.x without so much as a note or warning. Is there a plan to re-add support for this? Does OpenVPN3 have any sort of changelog documenting breaking changes from 2.x? Moreover, where does the official 3.x config reference live?

This has been raised as a breaking change in places such as https://community.openvpn.net/openvpn/ticket/1227 (with no response).

Client such as Viscosity, which is still based on 2.x, fully support this and it works great. It basically does a DNS resolution on client startup and adds the IPs that the name resolves to as IPv4s to the route table.

The motivation for using hostnames is strong: it is common to have a domain point to multiple underlying IPs. It is not a sane option to maintain multiple IPs all pointing to the same host in VPN config. Having a one-line option to specify a hostname is much much cleaner.

**Comment by dsommers** [comment]
Yes, this is intentional.  We do not plan to implement `allow-pull-fqdn` as that feature is quite dubious and error prone.  It may not behave as expected, where the the resolving might change in-session if the DNS entries changes during the lifetime of the session.  I'm not even sure current code in OpenVPN 2.4 does account for such a scenario, where it could even leave a messy routing table if this happens a few times.  Routing can also be applied before or after the tun adapter is configured. If configured before the tun interface is set up, routes will never change afterwards.

Another issue is that you might end up adding a lot of routes, if the DNS record dumps many entries at you.  And if you depend on public DNS services, your VPN client might pick up the wrong IP addresses if the DNS query responses are forged, which might lead to routing traffic outside the VPN instead of inside the tunnel.

These are just some of the issues this feature pulls in.  We rather recommend using a different approach for handling this.

One more saner approach is making the server side do the DNS lookup from its trusted DNS server and via a plug-in or `--client-connect` generate `push route` entries on-the-fly to the client.  Such an approach can also implement validation of the retrieved results, before the routes are pushed to the client. This moves the responsibility of ensuring the routes are correct to the server side instead of a fragile client setup.

**Comment by brsolomon-deloitte** [comment]
@dsommers thank you, I appreciate the explanation.

We are looking into `--client-connect`.

Briefly, let's say `domain.com` resolves to 3 IPs, would the script look something like this?

```
dig domain.com +short | xargs -r -I '{}' echo "route {}"
```

This generates 3 lines in `route x.x.x.x` format. Is the above acceptable as the content of `cmd`?

**Comment by dsommers** [comment]
The output of your client-connect script needs to result in a similar output as what you would put inside a `--client-config-dir` file.

This might get you closer:

     host -t A domain.com | awk '{ print "push \"route " $4 " 255.255.255.255\"" }'

**Comment by brsolomon-deloitte** [comment]
How's this?

```bash
#!/bin/bash

set -o pipefail

push_route_dynamic() {
    local outfile="$1"
    echo "using outfile $outfile"
    dig -4 -t A +short domain.com \
        | xargs -r -I '{}' echo 'push "route {} 255.255.255.255"' >> "$outfile"
}

# past last arg
push_route_dynamic "${@: -1}"
```

> If the script wants to generate a dynamic config file to be applied on the server when the client connects, it should write it to the file named by the last argument.

Is my interpretation of that correct?

**Comment by dsommers** [comment]
That script looks fine, but I haven't tested it.

And your interpretation of "last argument" seems correct.  It might be that you can now also use the `client_connect_config_file` environment variable (that arrived in OpenVPN 2.5, together with the possibility to do deferred script execution).  If your DNS lookup takes a little while, this current approach may affect other running tunnels - in that case, using a deferred execution will resolve that.

**Comment by cron2** [comment]
Hi,

On Tue, Feb 01, 2022 at 02:15:05PM -0800, David Sommerseth wrote:
> I'm not even sure current code in OpenVPN 2.4 does account for such 
> a scenario, where it could even leave a messy routing table if this 
> happens a few times.  

Installed routes in 2.x are stored in "resolved" format, so when cleaning
up it does not use DNS but cleans exactly what was installed.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
