### ISSUE TITLE
When the openvpn3 client connects, the network will be interrupted, but openvpn2 will not

### ISSUE THREAD

**Issue by yuluohuakai** [OpenVPN/openvpn3#281]
When the openvpn3 client connects, creating a tun network card will cause a brief network interruption. The reason is guessed that a default route is added, but the openvpn2 client does not cause a network interruption when connecting. Does anyone know the reason?

**Comment by dsommers** [comment]
* Please provide some logs, so we avoid guessing so much.  As root, run these commands with **no VPN sessions running**:

      # openvpn3-admin netcfg-service --config-set log-level 6
      # openvpn3-admin log-service --log-level 6

  Ensure that all the `openvpn3-service-*` files are not running _before_ you start the VPN session.  You can stop them using `kill -INT`.

  If you used `openvpn3 config-import`, `openvpn3-as` or `openvpn-connector-setup` to configure your VPN configuration, please use `openvpn3 config-manage --config CONFIG_NAME --log-level 6`.  Otherwise, add (or replace) the `verb` line in the config with `verb 6`.  Then start the VPN configuration.

  Use the command below to extract the relevant log data (as root):

      # openvpn3-admin journal --since 2023-09-14

  Please provide the log entries from the time where your last VPN session is started and the complete log towards the end.    

* Further, what do you mean with "brief network interruption"?  How do you notice this interruption?
* When you say you don't experience this with the `openvpn2 client`, do you mean you use the `/usr/bin/openvpn2` "emulator script" or the `/usr/sbin/openvpn` binary?  If the latter one, does your configuration file also include setting up DNS?

**Comment by yuluohuakai** [comment]
Thank you very much for your reply. I am using it on Windows. I have been pinging a public network address during use. As you can see from the picture, when openvpn is connected, the ping process is interrupted, thus judging the network interruption. . By looking at the route when connecting, you can see that openvpn is configured with a 0.0.0.0 route when it is started, which is the cause of the network interruption. However, in the openvpn 2.x version, the 0.0.0.0 route will not be generated when openvpn is started.
<img width="978" alt="image" src="https://github.com/OpenVPN/openvpn3/assets/22117627/6601b5d0-4142-4e75-b7f0-4cc53a693c27">
<img width="801" alt="image" src="https://github.com/OpenVPN/openvpn3/assets/22117627/d98e85f7-7382-441a-be3c-8cc59da6b857">

**Comment by jkroepke** [comment]
@novaflash

What about define a high metric as default that the route will be not have an impact by default?

Secondly use 0.0.0.0/1 and 128.0.0.0/1 routes to route the traffic over VPN, if requested (like `redirect-gateway def1`)

**Comment by novaflash** [comment]
Hello jkroepke,

Please refer to my explanation again very carefully. OpenVPN is not implementing the 0/0 route, Windows is doing that by itself, because the gateway is specified on the network interface. Therefore we have zero control over this route being added.

If we stop telling Windows to add gateway to the network interface, then the route doesn't appear, but then Windows will not trigger firewall logic correctly, and then we have different and new problems.

Again, if anyone has a better solution, we would love to hear it.

**Comment by jkroepke** [comment]
@novaflash but as I understand, the metric of the default route based on the metric from the interface. In Windows, interfaces can have interface metrics (`netsh interface ipv4 set interface metric`). If there is a high metric in the interface, the automatic route should also get an higher metric and should not be preferred by Windows.

I agree, its messy. But Windows is also messy here.

**Comment by novaflash** [comment]
Yeah I edited my earlier comment that that is a path we'll try and see if it will actually work, and not cause new headaches - because, you know, Windows.

**Comment by novaflash** [comment]
So just to update people here - better late than never - OpenVPN Connect v3.4.3 for Windows does include this particular fix. It's mentioned in the release notes here;

https://openvpn.net/vpn-server-resources/openvpn-connect-for-windows-change-log/
- Improved handling of unwanted 0.0.0.0/0 route added by Windows operating system

Hopefully it will deliver the solution for this particular issue.
