### ISSUE TITLE
Problem with DNS on Windows after unexpected process termination

### ISSUE THREAD

**Issue by savely-krasovsky** [OpenVPN/openvpn3#289]
So after some unexpected OpenVPN3-process termination (bug, kill, etc) local resources that has two IPs (both public and private) cannot resolve. For example `nslookup` works and returns correct IPs, but `ping` and browser don't work (because they use DNS Service apparently).

Currently it helps to connect again and disconnect properly after it. Then DNS functionality restores. It's okay as workaround. But in our case we use SSO to authorize, so user cannot even connect again. How this could be fixed? What commands does OpenVPN3 run after disconnect was initialized? Could we call those commands manually?

**Comment by L11R** [comment]
As usually, have got a-ha moment just after creating this issue.

OpenVPN3 creates record in registry for NRPM (Name Resolution Policy Messages). To fix DNS you need to manually remove all registry keys with OpenVPN prefix `OpenVPNDNSRouting`. They are located here: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig`

**Comment by L11R** [comment]
@lstipakov thanks for the answer. Well, our team is not very skilled with C++, so we just took OpenVPN3's `OpenVPNClient` class and built privileged agent around it using Go and SWIG wrapper. We listen for events and manage it with Connect/Disconnect/Pause/Resume.

It works pretty well with a few caveats:
1. Windows and Linux doesn't have build-in reconnect support (while macOS has MacLifeCycle class which pauses and resumes connection automatically).
2. We are not happy that `OpenVPNClient` for Windows does not allow us to manually select interface we want to use. It's probably okay if you use `ovpn-dco` driver, because only OpenVPN apps will use it, but in our case it's `wintun`. In that case OpenVPN3 randomly picks any `wintun` interface it will find. Or maybe we don't understand something.

We are currently in the process of fixing the first problem manually by using Network Link Manager for Windows (using Go's direct syscalls for calls and OLE IConnectionPoint sink interface to listen network related events) and NetworkManager DBus events for Linux (also there is an option to listen directly for Netlink kernel events).

But I'm a little scared by your answer. So we are using it not as you intended? Why would it even work for desktops if `OpenVPNClient` is mainly for mobile devices?

**Comment by lstipakov** [comment]
I don’t know your implementation, so cannot really say if it is more or less secure than ours. But on a general level it might be a good idea to follow principle of least privilege. We do it also in openvpn2-based OpenVPN-GUI Windows client. Lähetetty iPhonestaSavely Krasovsky ***@***.***> kirjoitti 8.12.2023 kello 16.35:﻿
@lstipakov yes, maybe I didn't understand agent term correctly. We use single privileged process that allows GUI app to manage TUN-interface and other network settings. Our case mostly covers Windows and macOS. I know that in case of Linux openvpn3-linux project does it more properly, but currently it's broken for the newer distros (OpenVPN/openvpn3-linux#171).
Does ours "agent" less secure than yours in case of Windows and macOS?

**Comment by lstipakov** [comment]
You need privileges only for limited set of operations, so you may want to reverse you question and ask instead "how can I setup routing etc with unprivileged process"?  Above I pointed to agent implementation - it is running as a separate process (as a service in Windows), functions as HTTP server and replies to 3 POST requests:
 - /tun-open
 - /tun-setup
 - /add-bypass-route

A fair amount of agent code is HTTP stack, which you get for free in Go I think. The rest employs `TunClient` class hierarchy, for which we don't have SWIG bindings. It should not be difficult to reimplement it in Go, though. 

The same approach is used in macOS - there is agent process, running as daemon and functioning as HTTP server.

With `dco-win` (same for Linux and FreeBSD modules) we have crypto and network communication in kernel, so if something goes wrong there we're in trouble. We put things into the kernel to avoid user space/kernel space context switch for every packet, which greatly improves performance but brings some risks, too. On the other hand, the kernel modules have limited functionality and we try to keep only performance-critical things there, delegating many things to userspace (or example, TLS handshake).

**Comment by L11R** [comment]
@lstipakov I see, thanks. A room for improvement for us. But does `OpenVPNClient` is able to run without root priveledges, but still able to reuse setup ready for use TUN interface?

**Comment by L11R** [comment]
@lstipakov we found out, that OpenVPN3 already supports ovpnagent while using as library. But for some reason it has not documented at all. Instead of rewriting ovpnagent in Go, we decided to compile agent using CMake target `ovpnagent` and add definition to `ovpnclillib`: `OPENVPN_COMMAND_AGENT`. It allows OpenVPN3 to establish TUN interface using agent.

I think it should be the default way of use for win/mac. Otherwise many people would misuse it.
