### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by busterbernstein** [OpenVPN/openvpn3#37]
Since the project works for various operating systems maybe add a release with the executables for each OS?

**Comment by dsommers** [comment]
This is primarily a source code based library.  This source code contains some rough reference implementations of this library.  We normally reference this openvpn3 code base as the OpenVPN 3 Core Library.  So there is no real executables to release in this regard.

Products implementing this library are currently the close-source apps for Android and iOS named "OpenVPN Connect" (they are essentially relicensing this code base).  And in addition we have an on-going work on an open source client primarily targeting Linux - [openvpn3-linux](https://github.com/OpenVPN/openvpn3-linux).  This client have not yet reached a production stable release, but its an on-going work here as well.  If you can make use of Fedora Copr repositories, the [openvpn3-client](https://copr.fedorainfracloud.org/coprs/dsommers/openvpn3/) an installable package is easily available from there.

Currently we have not managed to release any open source based clients for other platforms.  This is being planned for some platforms, but we have no ETA as of now.

Since this request is not applicable for this project, I'm closing it now.
