### ISSUE TITLE
Open VPN Connect (iOS) : RSA-SHA512 not found

### ISSUE THREAD

**Issue by qkdreyer** [OpenVPN/openvpn3#39]
Version : Open VPN Connect 1.2.9

While importing through Safari or Files application I'm getting the error message : 
```
crypto_alg: RSA-SHA512: not found
```

If this is revelant, here is my .ovpn file : 
```
dev tap
persist-tun
persist-key
cipher DES-EDE3-CBC
auth RSA-SHA512
tls-client
client
resolv-retry infinite
remote hostname.tld 1194 udp
lport 0
auth-user-pass
ns-cert-type server
comp-lzo adaptive

pull-filter ignore "dhcp-option DNS "
redirect-gateway def1

<ca>
 [Security-related line(s) omitted]
</ca>
setenv CLIENT_CERT 0
<tls-auth>
 [Security-related line(s) omitted]
</tls-auth>
 key-direction 1
```

**Comment by ordex** [comment]
Hello, this is the bug tracker of the OpenVPN 3 core library. For further help about OpenVPN Inc. commercial products, please refer to the forum (or their related bug tracker at): https://forums.openvpn.net/viewforum.php?f=32

This said, you are lucky because this error is coming from the library itself, therefore I can tell you that `RSA-SHA512` is not a valid value for `auth` and you should use `SHA512`.
`RSA-SHA512` is an OpenSSL thing.
