### ISSUE TITLE
OpenVPN 2 python wrapper error

### ISSUE THREAD

**Issue by andreiglingeanu** [OpenVPN/openvpn3#40]
Hello,

I'm trying to start a tunnel via the `openvpn2` wrapper script to a OpenVPN 2 to server. The command I'm running is that one (it works with the classic `openvpn` binary):

```sh
openvpn2  --config config.ovpn.txt --auth-user-pass auth.txt
```

For some kind of a reason, the Python script gets back with an error about wrong arguments:

```
/usr/bin/openvpn2: error: unrecognized arguments: --resolv-retry infinite --tun-mtu-extra 32 --tls-client
```

I've tried to dissect the Python script in order to find the source of the problem but I didn't found anything mentioning such args there.

Any help is highly appreciated, thanks!

**Comment by cron2** [comment]
Hi,

On Tue, Mar 13, 2018 at 12:01:01AM +0000, Andrei Glingeanu wrote:
> For some kind of a reason, the Python script gets back with an error about wrong arguments:
> 
> ```
> /usr/bin/openvpn2: error: unrecognized arguments: --resolv-retry infinite --tun-mtu-extra 32 --tls-client

openvpn 3 does not understand all possible options that openvpn 2.x has
-> go to your config file, and remove those named arguments.

--tls-client needs to be just "--client"

gert
-- 
now what should I write here...

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by andreiglingeanu** [comment]
Thank you very much for helping! This indeed helped, I'll adjust my configuration file to make it compatible with OpenVPN 3.

Is there anything I can further do in order to help? I feel like my problem already has a solution.

**Comment by dsommers** [comment]
If you're up to provide patches, that is the quickest way to see results :slightly_smiling_face: ... But please send them to openvpn-devel@lists.sourceforge.net for review, even though if it is a non-critical and not somehow security sensitive, I'm not too strict about it currently.  The project is still fairly fresh, and I want things to move forward reasonably quick.

Most of the Python stuff falls into the "non-critical" part, unless you touch anything related to key/certificate handling, the PKCS#11 stuff, username/password handling etc.  Option parsing is a grey area though, so if you want to be safe - mailing list is always the safest bet.  But I can review patches coming via GitHub before they're sent to the mailing list though.

Since this issue isn't strictly OpenVPN 3 Core related, but openvpn3-linux, I'll close this ticket now.  We can pick up the discussion there again whenever needed.

**Comment by andreiglingeanu** [comment]
Thanks for a very thorough clarification, very much appreciated! I can probably come up back with a possible patch for that once get more into it & gain a deeper understanding, thanks again.

**Comment by dsommers** [comment]
I've pushed out an updated openvpn3-linux tree, which improves the situation for `--tls-client` and `--resolv-retry`.  [Copr](https://copr.fedorainfracloud.org/coprs/dsommers/openvpn3/) builds completed as well.
