### ISSUE TITLE
openvpn3 non admin windows 10

### ISSUE THREAD

**Issue by lyhzhenhao2025** [OpenVPN/openvpn3#43]
Why can't I run OpenVPN on Windows from a non-admin user account?
Is there a better solution that does not require administrator privileges to complete the VPN connection?
Users can connect to VPN with a single click. Thanks.

**Comment by cron2** [comment]
Hi,

On Thu, Apr 12, 2018 at 08:47:27AM +0000, lyhzhenhao2025 wrote:
> Why can't I run OpenVPN on Windows from a non-admin user account?
> Is there a better solution that does not require administrator privileges to complete the VPN connection?
> Users can connect to VPN with a single click. Thanks.

First of all, you can run OpenVPN as non-admin just fine.

Then, this is the openvpn3 core library, not an end-user support forum.

Depending on which OpenVPN-based product you use (Viscosity, OpenVPN
Connect, OpenVPN 2.4 community edition) they all have their own support
channels or forums.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by lyhzhenhao2025** [comment]
Dear Gert,
    Thanks for your help.
    If the openvpn needs to have administrator rights, Windows 10 will not support it in future releases. I looked at the source code related to the needs of the routing and drivers, administrator privileges, so I do not know what to do.
    Thanks,
lee

________________________________
lyh_zhenhao@hotmail.com

**Comment by lyhzhenhao2025** [comment]
Thanks for your help.
If the openvpn needs to have administrator rights, Windows 10 will not support it in future releases. I looked at the source code related to the needs of the routing and drivers, administrator privileges, so I do not know what to do.

**Comment by cron2** [comment]
Hi,

On Thu, Apr 12, 2018 at 02:05:19AM -0700, lyhzhenhao2025 wrote:
> Dear Gert,
>     Thanks for your help.
>     If the openvpn needs to have administrator rights, Windows 10 will not support it in future releases. I looked at the source code related to the needs of the routing and drivers, administrator privileges, so I do not know what to do.

There is no "the openvpn".

OpenVPN *3* is a library, used by OpenVPN Connect.

OpenVPN *2* is used in the OpenVPN Community Edition.

Both products work very nicely on Windows 10 by means of a service that
runs with privileges and GUI and openvpn.exe run without privileges.

If that service is not running, you can run the GUI (for 2.4) with
admin privileges - but that is discouraged anyway because it will
increase your attack surface in case of programming bugs.


Still the wrong place to post your concerns.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by lyhzhenhao2025** [comment]
Can you explain in detail? I verified that openvpn-install-2.4.3-I601.exe requires administrator privileges. Can you send me an download address? thank you very much!     o(*￣︶￣*)o

**Comment by dsommers** [comment]
openvpn-install-2.4.3-I601 **IS NOT OpenVPN 3**.  (and openvpn-2.4.3 is also not the latest release)

@cron2 has already said:
> Then, this is the openvpn3 core library, not an end-user support forum.

and then

> Then, this is the openvpn3 core library, not an end-user support forum.

and then

> Still the wrong place to post your concerns.

Please find your proper support forum here: https://forums.openvpn.net/viewforum.php?f=22&sid=eb3bbddae38eae03949b5e78c9bc734a

You've basically just gone to a Lamborghini car dealer asking about Rolce Royce cars.  This place is the place to report **issues** (bugs, feature requests, etc) about **OpenVPN 3 Core Library**.  This is **not** a support forum.

**Comment by lyhzhenhao2025** [comment]
Thanks~
